name: Deploy to ECR
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: 862166188271.dkr.ecr.ap-south-1.amazonaws.com/dialogflow
  #VERSION: ${GITHUB_REF##*/}-${GITHUB_SHA::7}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: step
      run: |
        version:$(cat ./values.yaml | grep version: | awk '{print $2}'
        sed -i "s/$version/${GITHUB_REF##*/}-${GITHUB_SHA::7}/" ./values.yaml
