name: dev-workflow
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: printing the vars
        env:
          GIT_SHA: ${{ github.event.client_payload.sha }}
          BRANCH: ${{ github.event.client_payload.branch }}
        run: |
          VERSION=${BRANCH}-${GIT_SHA::7}
          version=$(cat ./values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/$VERSION/" ./values.yaml
      - name: commit and push changes for image version
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.MANU_PAT }}
          commit_message: Image version updated 



